-- Crear tabla empresa
CREATE TABLE empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    rut VARCHAR(20) NOT NULL,
    direccion VARCHAR(200),
    telefono VARCHAR(20),
    email VARCHAR(150),
    convenio_vigente BOOLEAN NOT NULL
);

-- Datos iniciales
INSERT INTO empresa (nombre, rut, direccion, telefono, email, convenio_vigente)
VALUES ('Salmones del Sur', '76.123.456-7', 'Puerto Montt', '652345678', 'contacto@salmones.cl', true);
INSERT INTO empresa (nombre, rut, direccion, telefono, email, convenio_vigente)
VALUES ('Logistica Austral', '77.987.654-3', 'Osorno', '649876543', 'info@logistica.cl', true);
INSERT INTO empresa (nombre, rut, direccion, telefono, email, convenio_vigente)
VALUES ('Turismo Patagonia', '75.456.789-1', 'Puerto Varas', '651234567', 'ventas@turismo.cl', false);