    spring.application.name=ms-asistencia
    server.port=8086
    spring.datasource.url=jdbc:h2:file:./data/asistencia
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=
    spring.jpa.hibernate.ddl-auto=none
    spring.h2.console.enabled=true
    spring.flyway.enabled=true
    springdoc.swagger-ui.path=/swagger
    springdoc.api-docs.path=/api-docs