# Nombre del microservicio
spring.application.name=ms-asistencia
# Puerto donde correrá este microservicio
server.port=8086
# Configuración de base de datos H2 en memoria
spring.datasource.url=jdbc:h2:file:./data/asistencia
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Desactivamos la creación automática de tablas con Hibernate
# porque queremos usar migraciones con Flyway
spring.jpa.hibernate.ddl-auto=none
# Permite abrir la consola web de H2
spring.h2.console.enabled=true
# Activa Flyway para ejecutar scripts SQL al iniciar
spring.flyway.enabled=true