CREATE TABLE Matricula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL,
    carrera_id BIGINT NOT NULL,
    seccion VARCHAR(50),
    fecha_matricula DATE DEFAULT CURRENT_DATE,
    estado VARCHAR(20) NOT NULL
);

CREATE UNIQUE INDEX uk_matricula_unica ON Matricula (estudiante_id, carrera_id);
INSERT INTO Matricula (estudiante_id, carrera_id, seccion, estado)VALUES (1, 1, 'A-1', 'ACTIVA');