CREATE TABLE Matricula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL,
    carrera_id BIGINT NOT NULL,
    seccion VARCHAR(50),
    fecha_matricula DATE,
    estado VARCHAR(50)
);

INSERT INTO Matricula (estudiante_id, carrera_id, seccion, fecha_matricula, estado)
VALUES(1, 1, 'A-1', '2025-01-10', 'ACTIVA');