CREATE TABLE matricula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL,
    carrera VARCHAR(100) NOT NULL,
    seccion VARCHAR(50),
    fecha_matricula DATE,
    estado VARCHAR(20)
);

-- Datos iniciales
INSERT INTO matricula (estudiante_id, carrera, seccion, fecha_matricula, estado)
VALUES (1, 'Informatica', 'A1', '2024-03-01', 'ACTIVA');
INSERT INTO matricula (estudiante_id, carrera, seccion, fecha_matricula, estado)
VALUES (2, 'Mecanica', 'B1', '2024-03-01', 'ACTIVA');