spring.application.name=ms-practica
server.port=8088
spring.datasource.url=jdbc:h2:file:./data/practica
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
spring.flyway.enabled=true