CREATE TABLE practica (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
estudiante_id BIGINT,
rut_estudiante VARCHAR(20) NOT NULL,
nombre_estudiante VARCHAR(100) NOT NULL,
email_estudiante VARCHAR(100) NOT NULL,
telefono_estudiante  VARCHAR(13) NOT NULL,
id_empresa BIGINT,
nombre_empresa VARCHAR(100) NOT NULL,
rut_empresa VARCHAR(20) NOT NULL,
direccion_empresa VARCHAR(100) NOT NULL,
telefono_empresa  VARCHAR(13) NOT NULL,
email_empresa VARCHAR(100) NOT NULL,
convenio_vigente_empresa BOOLEAN,
estado_arancel VARCHAR(100) NOT NULL
);
