CREATE TABLE carrera
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrera        VARCHAR(150) NOT NULL,
    asignaturas    VARCHAR(300) NOT NULL,
    mallas         VARCHAR(150) NOT NULL,
    prerrequisitos VARCHAR(300) NOT NULL
);

INSERT INTO carrera (carrera, asignaturas, mallas, prerrequisitos)
VALUES('Ingenieria en Informatica', 'Programacion, Base de Datos, Redes','Malla 2024', 'Programacion -> Base de Datos')