CREATE TABLE carrera(
    id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrera  VARCHAR(100) NOT NULL,
    asignaturas   VARCHAR(100) NOT NULL,
    mallas VARCHAR(100) NOT NULL,
    prerrequisitos VARCHAR(100) NOT NULL
);

INSERT INTO carrera (carrera, asignaturas, mallas, prerrequisitos) VALUES
('Ingenieria en Informatica',
'Programacion, Base de Datos, Redes',
'Malla 2024',
'Programacion -> Base de Datos')