CREATE TABLE asistencia (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
estudiante_id BIGINT,
rut_estudiante VARCHAR(20) NOT NULL,
nombre_estudiante VARCHAR(100) NOT NULL,
fecha_asistencia DATE
);
