CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50),
    password VARCHAR(100),
    role VARCHAR(20)
);

INSERT INTO usuario (username, password, role) VALUES ('admin', '1234', 'ADMIN');
INSERT INTO usuario (username, password, role) VALUES ('user', '1234', 'USER');