CREATE TABLE titulacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id BIGINT UNIQUE NOT NULL,
    fecha DATE NOT NULL,
    estado VARCHAR(30) NOT NULL
);

INSERT INTO titulacion (matricula_id, fecha, estado)
VALUES (1, DATE '2025-06-01', 'TITULADO');