CREATE TABLE titulacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id BIGINT,
    fecha VARCHAR(30),
    estado VARCHAR(30)
);

INSERT INTO titulacion (matricula_id, fecha, estado)
VALUES (1, '2025-06-01', 'TITULADO');