CREATE TABLE titulacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id BIGINT,
    fecha DATE,
    estado VARCHAR(30)
);

INSERT INTO titulacion (matricula_id, fecha, estado)
VALUES (1, DATE '2025-06-01', 'TITULADO');