-- Creamos la tabla estudiante
CREATE TABLE estudiante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    telefono VARCHAR(20),
    fecha_nacimiento DATE,
    fecha_registro DATE
);

-- Datos iniciales
INSERT INTO estudiante (rut, nombre, email, telefono, fecha_nacimiento, fecha_registro)
VALUES ('12.345.678-9', 'Carlos Perez', 'carlosp@gmail.com', '912345678', '2000-05-10', '2024-03-01');
INSERT INTO estudiante (rut, nombre, email, telefono, fecha_nacimiento, fecha_registro)
VALUES ('98.765.432-1', 'Emilia Cardenas', 'emicardenas@gmail.com', '987654321', '1999-08-22', '2024-03-01');
INSERT INTO estudiante (rut, nombre, email, telefono, fecha_nacimiento, fecha_registro)
VALUES ('11.222.333-4', 'Camila Rojas', 'camila@gmail.com', '956789123', '2001-01-15', '2024-03-01');