spring.application.name=ms-empresas
server.port=8089
# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:file:./data/empresas
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Hibernate NO crea tablas
spring.jpa.hibernate.ddl-auto=none
# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration