CREATE TABLE evaluacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id BIGINT NOT NULL,
    nota DOUBLE PRECISION NOT NULL
);

INSERT INTO evaluacion (matricula_id, nota)
VALUES (1, 5.5);
INSERT INTO evaluacion (matricula_id, nota)
VALUES (1, 6.0);
INSERT INTO evaluacion (matricula_id, nota)
VALUES (2, 3.8);