spring.application.name=ms-docente

server.port=8082

spring.datasource.url=jdbc:h2:file:./data/docentes-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.root=INFO
logging.level.cl.educore=DEBUG
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
